INSERT INTO Stocks (StockName, Symbol) VALUES ("3M Inc", "MMM");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Advanced Micro Devices", "AMD");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Aflac", "AFL");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Apple Common Stock", "AAPL");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Microsoft Corporation Common Stock", "MSFT");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Alphabet Inc", "GOOGL");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Amazon.com", "AMZN");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Tesla, Inc", "TSLA");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Meta Platforms", "FB");
INSERT INTO Stocks (StockName, Symbol) VALUES ("NVIDIA Corporation", "NVDA");
INSERT INTO Stocks (StockName, Symbol) VALUES ("JP Morgan Chase & Co.", "JPM");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Alibaba Group", "BABA");
INSERT INTO Stocks (StockName, Symbol) VALUES ("UnitedHealth", "UNH");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Walmart Inc", "WMT");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Bank Of American", "BAC");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Analog Devices Inc", "ADI");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Home Depot Inc", "HD");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Mastercard Incorporated", "MA");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Procter & Gamble", "PG");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Adobe Inc", "ADBE");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Netflix Inc", "NFLX");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Saleforce.com", "CRM");
INSERT INTO Stocks (StockName, Symbol) VALUES ("NetEase Inc", "NTES");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Walt Disney Company", "DIS");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Pfizer Inc", "PFE");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Exxon Mobil Cor", "XOM");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Nike Inc", "NKE");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Toyota Motor", "TM");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Thermo Fisher", "TMO");
INSERT INTO Stocks (StockName, Symbol) VALUES ("Eli Lily", "LLY");
INSERT INTO Stocks (StockName, Symbol) VALUES ("PayPal Holdings", "PYPL");